### ISSUE TITLE
[SR-15935] Resource files created by build tool plugins aren't handled properly

### ISSUE THREAD

**Issue by abertelrud** [apple/swift-package-manager#4345]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15935      |
   |Radar             | rdar://problem/89693335         |
   |Original Reporter | @abertelrud      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | @abertelrud      |
   |Priority          | Medium      |

   

   md5: ff3606a8574b3b65ab897c084d6bb004

  </details>

**Issue Description:**

In SwiftPM 5.6 and later, package plugin build tools can generate source files by defining build commands that have \`.swift\` source files as outputs. It is supposed to be possible to generate any of the kinds of output files that SwiftPM can handle, such as resources.

But specifying .strings files or .lproj directories as outputs does not seem to work in SwiftPM 5.6 — \`swift\` \`build\` emits a warning that it doesn't know what to do about that kind of file.

This bug report tracks making this work so that for example .strings files can be generated by built too plugins.

**Comment by doozMen** [comment]
I have asked this question too on the forum [Can the pluginWorkingDirectory contain an asset catalog - Development / Package Manager - Swift Forums](https://forums.swift.org/t/can-the-pluginworkingdirectory-contain-an-asset-catalog/63284)

Would love this to be solved! Any update?

**Comment by neonichu** [comment]
This should work as long as tools-version 5.7 or newer is used. Was fixed in #4306

**Comment by doozMen** [comment]
Ok will try again and check the tools version. But xcode 14.3 gives me a warning now that it has no rule applied for the json files in my asset catalog. Maybe an Xcode thing then.

**Comment by neonichu** [comment]
Right, I believe that's the tools-version < 5.7 behavior. If this isn't the issue, please report back, this should be working in both SwiftPM CLI and Xcode at this point.

**Comment by doozMen** [comment]
Ok so I have tested it and it works with version 5.7 but not for my use case. I had to do a workaround. I put an generated asset catalog in the pluginWorkindirectory with the structure below.

<img width="594" alt="Screenshot 2023-02-24 at 11 50 07" src="https://user-images.githubusercontent.com/686038/221160697-003834a5-d6d5-4578-bba1-9368a595bbf0.png">

This is because normally an asset catalog all files are `Contents.json` and this would cause duplicated files as SPM does not take the folder structure into account.
Luckily iOS does not care about the name of the json file and I can prefix it. Making it work.

This workaround works for me but It could be that SPM should support asset catalog structures too? If that is the case I can create an issue for that if you like? @neonichu

**Comment by doozMen** [comment]
@neonichu I did discover via #4306 that you need to use a `prebuild` comand and not a `build` command. I would like this tool not to run all the time. But I will continue this in the swift forum.  https://forums.swift.org/t/can-the-pluginworkingdirectory-contain-an-asset-catalog/63284
