### ISSUE TITLE
Metal files silently compiled

### ISSUE THREAD

**Issue by schwa** [apple/swift-package-manager#5822]
### Description

SwiftPM 5.3 added support to process .metal files using the resource functionality.

It seems that somewhere between SwiftPM 5.3 and 5.7 _all_ .metal files in a package are compiled into a default.metallib file

I cannot find any documentation on this behaviour. Is it expected? What swiftpm version was this feature added?

**Comment by neonichu** [comment]
Resources of known types are automatically handled, as per the [resources proposal](https://github.com/apple/swift-evolution/blob/main/proposals/0271-package-manager-resources.md#declaring-resources). 

Could you elaborate more on what the issue is? Also it sounds like you're saying the behavior changed between versions, what changed exactly?

**Comment by schwa** [comment]
Ah it was my understanding that the only way to compile metal was via resource.process. From the sounds of it seems SPM has _always_ automagically compiled .metal files then?

TBH it's kind of unclear from proposal that what the expectations of metal files are. Maybe some clarity on what files are considered known and are handled automatically?

Is it possible to opt out of automatic handling? (so we could process metal files ourselves with a plugin?)

**Comment by neonichu** [comment]
You should be able to use [excludes](https://developer.apple.com/documentation/packagedescription/target/exclude). 

I'm not 100% sure, but it might also mean the `Target` APIs wouldn't include these files and you would need to look for them manually on the file system in your plugin implementation.

**Comment by neonichu** [comment]
BTW, the proposal was intentionally not descriptive about specific file types since we didn't want to (and couldn't) define concrete Xcode behavior in there. The [documentation](https://developer.apple.com/documentation/xcode/bundling-resources-with-a-swift-package) on resources in Xcode is a little bit more clear, but it unfortunately also doesn't really have an exhaustive list of file types which are handled automatically.

**Comment by schwa** [comment]
Yeah fair enough. Maybe then make .process() fail if it tries to process file that should be automatically handled? Can probably close out this ticket but yeah it is a bit confusing.
