### ISSUE TITLE
swift package generate-xcodeproj

### ISSUE THREAD

**Issue by rickhohler** [apple/swift-package-manager#6640]
**Describe the bug**
Run `swift package generate-xcodeproj` on my Swift Library project.

**Steps To Reproduce**
1. Command line prompt
2. Run command `swift package generate-xcodeproj`

**Expected behavior**
Command should generate an Xcode project.

**Screenshots**

```zsh
rickyhohler% swift package generate-xcodeproj 
warning: Xcode can open and build Swift Packages directly. 'generate-xcodeproj' is no longer needed and will be deprecated soon.
warning: Xcode project generation does not support conditional target dependencies, so the generated project might not build successfully. The offending targets are: SwiftSyntaxParser.
error: InternalError(description: "Internal error. Please file a bug at https://bugs.swift.org with this info. binary not supported")
```

**Environment (please fill out the following information)**
 - OS: MacOS Monterey 12.5.1 (21G83)
 - Xcode Version/Tag/Branch:  Xcode Version 14.0 (14A309)

**Additional context**
My library does use the SwiftSyntax library for parsing Swift code.

```swift
    dependencies: [
        .package(url: "https://github.com/apple/swift-syntax.git", exact: "0.50600.1"),
    ],
    targets: [
        .target(
            name: "PlumKit",
            dependencies: [
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxParser", package: "swift-syntax")
            ]
        ),
        .testTarget(
            name: "PlumKitTests",
            dependencies: [
                "PlumKit"
            ]
        ),
    ]
```

**Comment by neonichu** [comment]
You can open packages in Xcode directly, e.g. by double-clicking `Package.swift`.

**Comment by nerzh** [comment]
> You can open packages in Xcode directly, e.g. by double-clicking `Package.swift`.

yes, but xcode has a bunch of children's bugs that have not been fixed for more than a year. For example, I am now looking for a way to work with dependencies through a framework in which there will only be an SPM library, and I want to write all the dependencies in it with my hands. This is necessary for me because periodically the latest versions of packages are not pulled together with me or with a project friend. Now everything is fine with me, but with a friend on the same branch of the repository - xcode pulls old packages. And xcode 15 beta - completely forcibly erases all versions of packages on version 1.0.0. As a result, it turns out that we cannot work as a team. We have already tried all the ways to fix it. The last option is to abandon SPM inside XCODE and use the library as a separate xcodeproj with dependencies inside the workspace.

**Comment by tmaly1980** [comment]
Since generate-xcodeproj is removed from 14.3.1, how do I create an xcodeproj for a swift package? I need that to run automated tests in CircleCI.

**Comment by LucianoPAlmeida** [comment]
> Since generate-xcodeproj is removed from 14.3.1, how do I create an xcodeproj for a swift package? I need that to run automated tests in CircleCI.

Is there any specific reason you need an xcodeproj for that? Because you would be able to run tests on a package using `swift test` in the command-line IIRC.

**Comment by neonichu** [comment]
`xcodebuild test` also works on packages, you just need to specify a scheme since otherwise it assumes you have an Xcode project. You can use `xcodebuild -list` to see the available auto-generated schemes for your package.

**Comment by RockyCognizant** [comment]
> > Since generate-xcodeproj is removed from 14.3.1, how do I create an xcodeproj for a swift package? I need that to run automated tests in CircleCI.
> 
> Is there any specific reason you need an xcodeproj for that? Because you would be able to run tests on a package using `swift test` in the command-line IIRC.

I surely prefer `swift test` but I also need to run unit tests over simulator but `swift test` can only run macOS/Linux.
I can see a `.swiftpm` hidden folder with a default workspace inside of it, but I really like to learn for these default settings:
- assuming we have a fresh new swift package, contains only sources, tests and a package.swift
- we need to run a CI/CD for swift test in a simulator.

Before Swift 5.7, I can do `swift package generate-xcodeproj` then `xcodebuild test` with a simulator, but since Swift 5.8, everything changed. Please help. thanks.

**Comment by neonichu** [comment]
See above `xcodebuild test` works on packages. If there are issues with that or missing docs, please report them through http://feedbackassistant.apple.com
