### ISSUE TITLE
Can't add targets from other package to products.targets

### ISSUE THREAD

**Issue by miku1958** [apple/swift-package-manager#6766]
### Description

For example, I have a package like:
```
let package = Package(
  name: "APackage",
  platforms: [
    .macOS(.v11),
  ],
  products: [
    .library(
      name: "AProduct",
      type: .static,
      targets: [
        "A",
        "B",
      ]
    ),
  ],
  dependencies: [
    .package(name: "B", path: "../../../../packages/B")
  ],
  targets: [
    .target(
      name: "A",
      dependencies: [
        "B"
      ]
    )
  ]
)
```
Xcode/swift build will give me this error:
```
target 'B' referenced in product 'AProduct' could not be found; valid targets are: 'A'
```

### Expected behavior

A, B can be packed to AProduct and release together

### Actual behavior

target 'B' referenced in product 'AProduct' could not be found; valid targets are: 'A'

**Comment by neonichu** [comment]
How does B look like?

**Comment by miku1958** [comment]
B is another local package where we plan to separate the entire project to a different location to keep the original path structure

**Comment by neonichu** [comment]
Right, but what is in B concretely? I think the error message might be misleading here, it should never be possible to access a target from another package, only products.

**Comment by miku1958** [comment]
So, in B, the product has the same name as the target, and the "B" from the dependency is a product and not a target?

**Comment by neonichu** [comment]
I wonder if the `name` parameter messes with this, could you try removing `name: "B"` from the dependency declaration

**Comment by miku1958** [comment]
Same error

**Comment by MaxDesiatov** [comment]
@miku1958 would you be able to supply a self-contained package that reproduces this attached as an archive to this issue? Thanks!

**Comment by miku1958** [comment]
Sure, will do one asap, busy lately.

**Comment by miku1958** [comment]
[Archive.zip](https://github.com/apple/swift-package-manager/files/12299172/Archive.zip)
@MaxDesiatov I have created 2 empty packages Test and Test2, where Test2 is a dependency of Test.

**Comment by MaxDesiatov** [comment]
Firstly, in your archive you have `"Text2"` instead of `"Test2"` in the array of `dependencies` for the `Test` target.

Secondly, the error message you've provided is expected. A product is composed of targets in the same package. If you need to use public code from `Test2` in the `Test` target, specify it in the `dependencies` array of the corresponding target declaration, not in the `targets` array of product declarations.

Does that resolve your issue?

**Comment by neonichu** [comment]
Not sure, I'm a bit reluctant to reach out to another package for validation here since the `targets` property is firmly localized to the current package. There could also be cases where there are multiple matches since targets do not have to necessary be unique anymore across the graph due to module aliasing.
