### ISSUE TITLE
Unexpected packages are being added when integrating SwiftLint.

### ISSUE THREAD

**Issue by preciouslogic** [apple/swift-package-manager#7310]
### Description

I am using Swift Package Manager to add SwiftLint to my project. I am using the latest Xcode 15.2, but I am facing a weird issue. SwiftPM is adding some extra dependencies to the project, which should not happen as I am only adding one library, which is SwiftLint. This issue is only occurring for the SwiftLint library and not for other libraries. For example, I tested with Alamofire, and in that case, only the Alamofire library is being added. Please check the images for a visual representation of the issue and also refer to a sample project where you can see the problem.

### Expected behavior

Should add the SwiftLint dependency to the project.

### Actual behavior

Adding Unexpected packages.

<img width="258" alt="Screenshot 2024-02-01 at 09 52 27" src="https://github.com/apple/swift-package-manager/assets/6730214/17030fad-2323-4f9f-b9e7-2306981f87ff">
<img width="865" alt="Screenshot 2024-02-01 at 09 52 35" src="https://github.com/apple/swift-package-manager/assets/6730214/0ad28ab3-66f9-4289-81cc-2eaa369fa178">

### Steps to reproduce

Sample project.

[SPMSwiftLintIssue.zip](https://github.com/apple/swift-package-manager/files/14122593/SPMSwiftLintIssue.zip)

### Swift & OS version (output of `swift --version ; uname -a`)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
Darwin MacBook-Pro 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

**Comment by MaxDesiatov** [comment]
Hi @preciouslogic, thank you for filing the issue. Is this reproducible for you with any of SwiftPM command line tools, like `swift build` or `swift test`? If not, this seems to be an Xcode-specific issue to me.

This GitHub repository is dedicated to development of SwiftPM as an open-source project and has no relation to Xcode. For the latter you'd have to file an issue at http://feedbackassistant.apple.com.

**Comment by MaxDesiatov** [comment]
The libraries you see on the screenshot are dependencies of SwiftLint, as specified in its [`Package.swift`](https://github.com/realm/SwiftLint/blob/f0c1780b5355ddcd7048acb540946b2c5040d03a/Package.swift#L25) manifest. There's no way to add only SwiftLint without libraries that it depends on, otherwise SwiftLint won't build. If you're concerned about those dependencies, it would be more appropriate to file an issue on SwiftLint's repository.

You can compare this to [Alamofire's `Package.swift`](https://github.com/Alamofire/Alamofire/blob/master/Package.swift), which doesn't specify any dependencies.
